function showAlert() {
    let outputDiv = document.getElementById("output");
    window.alert("This Alert Generated By Window Function");
    outputDiv.innerHTML+="Clicked an Alert Box <br>"
    
}

function showConfirm() {
    let outputDiv = document.getElementById("output");
    if (window.confirm("Are you sure you want to proceed?")) {
        outputDiv.innerHTML += "User clicked OK<br>";
    } else {
        outputDiv.innerHTML += "User clicked Cancel<br>";
    }
}

function showPrompt() {
    let userInput = window.prompt("Please enter your name:", "Arjun K");
    let outputDiv = document.getElementById("output");
    if (userInput!=null) {
        outputDiv.innerHTML += "Hello " + userInput + "<br>";
    } else {
        outputDiv.innerHTML += "You didn't entered any Name <br>";
    }
    
}

let intervalID;

function startInterval() {
    let outputDiv = document.getElementById("output");
    intervalID = window.setInterval(function() {
        outputDiv.innerHTML += "Message appears every 3 seconds.<br>";
    }, 3000);
}

function stopInterval() {
    let outputDiv = document.getElementById("output");
    outputDiv.innerHTML += "Interval stopped.<br>";
    window.clearInterval(intervalID);
}

function openNewWindow() {
    let outputDiv = document.getElementById("output");
    outputDiv.innerHTML += "Opening a new window...<br>";
    window.open("https://www.javabykiran.com", "_blank");
}

function reloadWindow() {
    let outputDiv = document.getElementById("output");
    outputDiv.innerHTML += "Reloading the window...<br>";
    window.location.reload();
}

function scrollToPosition() {
    let outputDiv = document.getElementById("output");
    outputDiv.innerHTML += "Scrolling to position...<br>";
    window.scrollTo(0, 500);
}

let timeoutID;

function redirectToURL() {
    let outputDiv = document.getElementById("output");
    outputDiv.innerHTML += "Redirecting to Desiphools...<br>";
    window.location.href = "https://desiphools.netlify.app/";
}

function printWindowDimensions() {
    let outputDiv = document.getElementById("output");
    outputDiv.innerHTML += "Your Current Window ==> <b>Width:</b> " + window.innerWidth + " & <b>Height:</b> " + window.innerHeight + "<br>";
}

